apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdpl
  template:
    metadata:
      labels:
        app: orderdpl
    spec:
      containers:
        - name: menudpl
          image: sachetwasti61/orderfood
          ports:
            - containerPort: 8072
          env:
            - name: MENU_MONGO_URL
              valueFrom:
                configMapKeyRef:
                  key: menu_mongo_url
                  name: menu-cm
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: bucket_name
                  name: menu-cm
            - name: SECURE_KEY
              valueFrom:
                configMapKeyRef:
                  key: secure_key
                  name: secure-key-cm
---
apiVersion: v1
kind: Service
metadata:
  name: ordersrv
spec:
  selector:
    app: orderdpl
  ports:
    - port: 8072
      targetPort: 8072